Llama API
Knox-AAU/FunctionalityLayer_Chatbot pull request #28
Opened 2023-11-30 12:35 UTC by thomasbjeldbak

2023-11-30 12:37 UTC, DPPaladin submitted a review, later dismissed
Nice dude

2023-12-01 07:57 UTC, Ellleby approved these changes, later dismissed

2023-12-01 08:09 UTC, Ilum1 requested changes
Vi skal lige have styr på hvordan Llama skal ligges ind i docker imaget før vi merger

2023-12-05 09:29 UTC, Ilum1 approved these changes

2023-12-05 09:33 UTC, merged